create table person (
    id int8 generated by default as identity,
    gender varchar(255),
    name varchar(255),
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    primary key (id)
);
create sequence hibernate_sequence start 1 increment 1;
