create table car (
    id int8 generated by default as identity,
    name varchar(255),
    model varchar(255),
    primary key (id)
);

create table audit.car_aud (
    id int8 not null,
    rev int4 not null,
    revtype int2,
    name varchar(255),
    model varchar(255),
    primary key (id, rev)
);
